app <- ShinyDriver$new("../")
app$snapshotInit("test_radioSwitchButtons")

app$setInputs(std = "no")
app$setInputs(other = "no")
app$snapshot()
app$setInputs(other = "maybe")
app$snapshot()
app$setInputs(small = "bold")
app$snapshot()
app$setInputs(small = "italic")
app$snapshot()
app$setInputs(small = "plain")
app$snapshot()
app$setInputs(make_yes = "click")
app$snapshot()
app$setInputs(simple = "no")
app$snapshot()
app$setInputs(other = "yes")
app$setInputs(make_yes = "click")
app$snapshot()
