app <- ShinyDriver$new("../")
app$snapshotInit("buttonGroupTest")

app$setInputs(button_radio = "will")
app$snapshot()
app$setInputs(button_radio = "lucas")
app$snapshot()
app$setInputs(button_checkbox = "will")
app$setInputs(button_checkbox = c("will", "mike"))
app$snapshot()
app$setInputs(button_checkbox = c("eleven", "will", "mike"))
app$snapshot()
app$setInputs(button_checkbox = c("eleven", "mike"))
app$setInputs(button_checkbox = c("eleven", "mike", "lucas"))
app$snapshot()
app$setInputs(button_init = c("eleven", "lucas"))
app$snapshot()
app$setInputs(button_icon = "left")
app$setInputs(button_icon = "right")
app$snapshot()
app$setInputs(button_html = "bold")
app$setInputs(button_html = c("bold", "strikethrough"))
app$snapshot()
app$setInputs(button_style = "Will Byers")
app$snapshot()
