app <- ShinyDriver$new("../")
app$snapshotInit("test-pager")

app$setInputs(`pager-page_next` = "click")
app$setInputs(`pager-page_next` = "click")
app$snapshot()
app$setInputs(`pager-page_next` = "click")
app$snapshot()
app$setInputs(page_break = 5)
app$setInputs(page_break = 4)
app$snapshot()
app$setInputs(page_break = 6)
app$snapshot()
app$setInputs(`pager-page_next` = "click")
app$snapshot()
app$setInputs(`pager-page_extra_next` = "click")
app$snapshot()
app$setInputs(`pager-page_extra_prev` = "click")
app$snapshot()
app$setInputs(`pager-page_001` = "click")
app$snapshot()
app$setInputs(`pager-page_prev` = "click")
app$snapshot()
app$setInputs(`pager-page_extra_prev` = "click")
app$snapshot()
app$setInputs(page_break = 5)
app$setInputs(`pager-page_005` = "click")
app$setInputs(`pager-page_006` = "click")
app$snapshot()
